<?xml version="1.0"?>
<robot name="3R_manipulator" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />

    <!-- Properties -->
    <xacro:property name="link_radius" value="0.0125" /> 
    <xacro:property name="link_length" value="0.1" />
    <xacro:property name="payload_radius" value="0.0125" /> 


    <!-- Base footprint and link -->
    <link name="base_footprint"/>

    <joint name="base_joint" type="revolute">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${link_radius}" rpy="${pi/2} 0 0"/>
        <limit effort="100.0" velocity="10.0" lower="${-pi/2}" upper="${pi/2}" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="base_link">
            <visual>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.1" r="${link_radius}" h="${link_length}" 
                                    xyz="0 0 0" rpy="0 0 0" />
        </link>

    <joint name="base_link2_joint" type="fixed">
        <parent link="base_link"/>
        <child link="link2"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 0 "/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="link2">
            <visual>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
                <material name="blue"/>
                <origin xyz="0 0 ${link_length/2}" rpy="0 0 0 "/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.1" r="${link_radius}" h="${link_length}" 
                                    xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="link2_joint2" type="revolute">
        <parent link="link2"/>
        <child link="joint2_link"/>
        <origin xyz="0 0 ${link_length}" rpy="${pi/2} 0 0"/>
        <limit effort="100.0" velocity="10.0" lower="${-pi/2}" upper="${pi/2}" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="joint2_link">
            <visual>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
                <material name="black"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.1" r="${link_radius}" h="${link_length}" 
                                    xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="joint2_link3_joint" type="fixed">
        <parent link="joint2_link"/>
        <child link="link3"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 0 "/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="link3">
            <visual>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
                <material name="blue"/>
                <origin xyz="0 0 ${link_length/2}" rpy="0 0 0 "/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.1" r="${link_radius}" h="${link_length}" 
                                    xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="link3_joint3" type="revolute">
        <parent link="link3"/>
        <child link="joint3_link"/>
        <origin xyz="0 0 ${link_length}" rpy="${pi/2} 0 0"/>
        <limit effort="100.0" velocity="10.0" lower="${-pi/2}" upper="${pi/2}" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="joint3_link">
            <visual>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.1" r="${link_radius}" h="${link_length}" 
                                    xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="joint3_link4_joint" type="fixed">
        <parent link="joint3_link"/>
        <child link="link4"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 0 "/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="link4">
            <visual>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
                <material name="blue"/>
                <origin xyz="0 0 ${link_length/2}" rpy="0 0 0 "/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${link_radius}" length="${link_length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.1" r="${link_radius}" h="${link_length}" 
                                    xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="link4_payload" type="fixed">
        <parent link="link4"/>
        <child link="payload"/>
        <origin xyz="0 0 ${link_length + payload_radius}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

     <link name="payload">
        <visual>
            <geometry>
                <sphere radius="${payload_radius}"/>
            </geometry>
            <material name="grey"/>
            <origin xyz="0 0 0" rpy="0 0 0 "/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${payload_radius}"/>
            </geometry>
        </collision>
        <xacro:sphere_inertia m="0.5" r="${payload_radius}" 
                                    xyz="0 0 0" rpy="0 0 0" />
    </link>

</robot>